### PR TITLE
Gave the GUI components proper names

### PR DESCRIPTION
**Pull request by NicholasSheehan**
Also renamed the callback methods that are used to something more sensible

### CODE REVIEW

**Comment by NicholasSheehan** [comment]
Just to note, that Rider autoformatted `Form1.Designer.cs` hence the large diff

**Comment by laurinneff** [comment]
You could've only added the changes to WindowsFormsApp9/Form1.cs that the diff isn't as large

**Comment by 3top1a** [comment]
Honestly, all of your commits aren't needed, yet should be approved for clarity.

**Comment by NicholasSheehan** [comment]
> Honestly, all of your commits aren't needed, yet should be approved for clarity.

I agree, adding to a clean codebase is a lot easier than adding to a messy codebase

**Pull request merged**
