### PR TITLE
Added some stuff. made it a lot better

### PR DESCRIPTION
**Pull request by 3top1a**
Username detection 
Background detection
User's profile picture detection

### CODE REVIEW

**Review by nickmartin1ee7 — APPROVED** [review]

**Review by ITCMD — APPROVED** [review]
Looks great, I see no issues.

**Comment by 3top1a** [comment]
*can you please merge the version before the comment by ITCMD?

**Comment by ITCMD** [comment]
Why? What'd I do? (just kidding)

**Comment by Pickfordmatt** [comment]
Can you fix the conflicting files please?

**Comment by GGORG0** [comment]
How to get your project files from GitHub?

**Comment by Pickfordmatt** [comment]
> How to get your project files from GitHub?

Dude this is not the place to ask questions.

**Comment by 3top1a** [comment]
I have removed this form and I'm making a new one

**Pull request closed without merging**
